# linear reg model and how does it work on real world data

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('placementREG.csv')


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   cgpa     200 non-null    float64
 1   package  200 non-null    float64
dtypes: float64(2)
memory usage: 3.3 KB


In [5]:
df

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [6]:
#no nan value 

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 

In [8]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0],df.iloc[:,[-1]],test_size=0.2)

In [9]:
X_train

5      7.89
193    4.57
167    8.13
79     7.18
0      6.89
       ... 
110    8.18
159    8.71
136    5.64
121    6.50
144    6.17
Name: cgpa, Length: 160, dtype: float64

In [10]:
#simple linear reg taking only one col as input
lr= LinearRegression ()

In [11]:
lr.fit(X_train.values.reshape(-1,1),y_train)

LinearRegression()

In [12]:
ypred=lr.predict(X_test.values.reshape(-1,1))

In [13]:
ypred

array([[1.77659608],
       [3.73976181],
       [3.07050077],
       [1.74313303],
       [3.36051388],
       [2.39566255],
       [2.23392446],
       [3.50552044],
       [3.53340632],
       [3.76207051],
       [2.07218637],
       [2.71356154],
       [3.91823142],
       [2.97568878],
       [2.50720605],
       [3.68956723],
       [2.52393758],
       [2.71356154],
       [3.32705083],
       [2.41797125],
       [2.3845082 ],
       [3.2433932 ],
       [3.89034554],
       [3.51667479],
       [3.08723229],
       [2.39008537],
       [4.21382172],
       [2.84741375],
       [4.26959347],
       [2.57413216],
       [3.27127908],
       [4.15804996],
       [3.20993015],
       [2.97011161],
       [2.49047453],
       [3.08723229],
       [2.10564943],
       [2.36219949],
       [2.99799749],
       [3.650527  ]])

In [14]:
lr.intercept_#b

array([-0.89487092])

In [15]:
lr.coef_#m

array([[0.55771754]])

In [ ]:
# now creating  a class for simple lr sam eway as sk learn work 

In [16]:
class mineLR:
    
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self,X_train,y_train):
        
        num = 0
        den = 0
        
        for i in range(X_train.shape[0]):
            
            num = num + ((X_train.values[i] - X_train.mean())*(y_train.values[i] - y_train.mean()))
            den = den + ((X_train.values[i] - X_train.mean())*(X_train.values[i] - X_train.mean()))
        
        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)       
    
    def predict(self,X_test):
        
        print(X_test)
        
        return self.m * X_test + self.b


In [17]:
lr1=mineLR()

In [18]:
lr1.fit(X_train,y_train) # same value of m and b as got above

package    0.557718
dtype: float64
package   -0.894871
dtype: float64


In [19]:
X_train.values[0]

7.89

# TYPES OF ACCURACY AND LOSS MATRIX:
IE R2 SCORE MSE ,MAE, RMSE, ADJUSTED R2 SCORE THEY ALL TELL HOW MUCH ERROR OUR MODEL ID PRODUCING IN THEIR OWN WAY R2 BY 